img_filename: 
  value: fall_landscape.jpg
  description: picture file to process (.jpg)

tile_number_width:
  value: 50
  description: number of tiles to have across the width of the picture

color_number:
  value: 16
  description: number of different colors or fabrics

tile_size:
  value: 2
  description: size in inch of each square tile (i.e. 2 for 2x2" tiles in finished quilt)

colorspace:
  value: YUV
  description: '[advanced] colorspace to use in reducing the number of colors in the original picture (some examples are YUV, RGB, HSV)'

colorspace_max_colors:
  value: 500
  description: '[advanced] maximum number of colors returned after colorspace reduction'

grid_block_size:
  value: 8
  description: block size in tiles (i.e. 8 for instructions for blocks of 8x8 tiles)
